version: "3.8"

services:
  nodejs-app:
    image: node:latest
    container_name: SilverTongued
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
